name: Comment Handler
on:
  issue_comment:
    types: [created]
jobs:
  handle:
    runs-on: ubuntu-latest
    steps:
      - name: Process
        run: echo ""
        env:
          BODY: ${{ github.event.comment.body }}